security:
    # Configuration des hashers pour les mots de passe
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    # Fournisseurs d'utilisateurs
    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email  # Correspond au champ utilisé pour l'authentification (email)

    # Pare-feu (firewalls)
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login       # Route pour afficher la page de connexion
                check_path: app_login       # Route pour traiter le formulaire de connexion
                username_parameter: email   # Nom du champ utilisé pour l'email
                password_parameter: password # Nom du champ utilisé pour le mot de passe
                enable_csrf: true           # Sécurité CSRF activée
                default_target_path: app_event
            logout:
                path: app_logout            # Route pour se déconnecter
                target: app_login           # Redirection après déconnexion

    # Contrôle d'accès
    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }   # Accès à /admin réservé aux administrateurs
        - { path: ^/profile, roles: ROLE_USER } # Accès à /profile réservé aux utilisateurs authentifiés
        - { path: ^/organizer, roles: ROLE_ORGANIZER }
        - { path: ^/locator, roles: ROLE_LOCATOR }
        - { path: ^/user, roles: ROLE_USER }
